PRETRAINED_MODEL_PATH = 'pretrained_models'
MODEL_DIR = "model"

CONFIG_NAME = "FIND_PHONE_CONFIG"
LABELS_FILE = "labels.txt"
IMAGE_HEIGHT = 326
IMAGE_WIDTH = 490
BBOXSIZE = 0.02
TRAIN_DATA_SPLIT_RATIO = 0.8
VALUATION_DATA_SPLIT_RATIO = 0.2